import "./globals.css";
import SmoothScroll from "./providers/SmoothScroll";
import DotBackground from "@/components/DotBackground/DotBackground";
import "@/components/DotBackground/DotBackground.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  other: {
    link: [
      {
        rel: "preload",
        as: "image",
        href: "/her0-bg.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: "'Inter', sans-serif",
          padding: 0,
          margin: 0,
          overflow: "hidden", // ✅ IMPORTANT
        }}
      >
        {/* GLOBAL DOT BACKGROUND */}
        <DotBackground />

        {/* Smooth scrolling (side-effect only) */}
        <SmoothScroll />

        {/* ✅ LOCOMOTIVE SCROLL CONTAINER */}
        <div
          data-scroll-container
          style={{
            position: "relative",
            zIndex: 1,
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}