import "./globals.css";
import SmoothScroll from "./providers/SmoothScroll";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{
        fontFamily: "'Inter', sans-serif",
        padding: 0,
        margin: 0,
      }}>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  )
}
