import "./globals.css";
import SmoothScroll from "./providers/SmoothScroll";
import DotBackground from "@/components/DotBackground/DotBackground";
import "@/components/DotBackground/DotBackground.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          fontFamily: "'Inter', sans-serif",
          padding: 0,
          margin: 0,
        }}
      >
        {/* Background */}
        <DotBackground />

        {/* Smooth Scroll */}
        <SmoothScroll />

        {/* Locomotive Container */}
        <div
          data-scroll-container
          style={{
            position: "relative",
            zIndex: 1,
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}